In [1]:
import pandas as pd
import os

# Directory where the CSV files are located
directory = r'C:\Users\yonatanam\Desktop\NBA\Data'

# List all CSV files in the directory
csv_files = [os.path.join(directory, file) for file in os.listdir(directory) if file.endswith('_Opp.csv')]

# Initialize an empty list to store DataFrames
dfs = []

# Loop through each CSV file
for file in csv_files:
    # Extract year from the file name
    year = os.path.basename(file).split('_')[0]
    
    # Read CSV file
    df = pd.read_csv(file)
    
    # Add a new column 'Year' with the extracted year
    df['Year'] = year
    
    # Append the DataFrame to the list
    dfs.append(df)

# Concatenate all DataFrames into one
opponent_avg_by_year_data = pd.concat(dfs, ignore_index=True)

#the combined DataFrame

opponent_avg_by_year_data

,Rk,Team,G,MP,FG,FGA,FG%,3P,3PA,3P%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,1.0,Detroit Pistons*,82,242.7,33.5,76.5,0.438,3.5,10.2,0.344,...,10.5,30.8,41.3,18.3,6.9,4.3,14.0,23.2,87.7,2002
1,2.0,New Jersey Nets*,82,240.9,33.6,78.8,0.427,5.2,14.5,0.359,...,11.4,30.0,41.4,19.6,8.5,5.2,16.6,22.9,90.1,2002
2,3.0,San Antonio Spurs*,82,241.8,34.9,81.7,0.427,4.3,12.7,0.339,...,12.5,28.3,40.9,19.0,8.1,5.1,15.0,23.4,90.4,2002
3,4.0,Miami Heat,82,241.8,33.1,75.7,0.437,5.0,14.0,0.353,...,10.6,31.5,42.2,18.1,7.6,5.3,14.3,20.4,90.6,2002
4,5.0,New Orleans Hornets*,82,242.7,34.8,79.5,0.438,4.1,12.2,0.338,...,11.1,28.9,40.0,19.9,7.9,5.2,14.6,21.4,91.8,2002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,27.0,Detroit Pistons,82,241.5,43.1,88.1,0.489,12.0,33.3,0.360,...,11.0,33.7,44.7,25.8,7.7,5.5,13.5,21.0,118.5,2022
645,28.0,Houston Rockets,82,240.9,42.4,88.1,0.482,14.5,38.8,0.374,...,10.5,31.0,41.5,26.1,8.8,6.2,13.2,20.6,118.6,2022
646,29.0,Indiana Pacers,82,240.9,43.3,89.3,0.485,12.4,33.3,0.373,...,12.1,33.2,45.3,26.4,7.9,5.3,15.1,20.2,119.5,2022
647,30.0,San Antonio Spurs,82,242.1,46.1,91.0,0.507,12.6,32.3,0.391,...,10.7,34.3,45.0,26.8,8.1,5.3,13.8,18.5,123.1,2022
648,NaN,League Average,82,241.8,42.0,88.3,0.475,12.3,34.2,0.361,...,10.4,33.0,43.4,25.3,7.3,4.7,14.1,20.0,114.7,2022

In [7]:
opponent_avg_by_year_data.to_csv(os.path.join(directory, 'opponent_avg_by_year_data.csv'), index=False)